import { BuyingChemicals } from "../../views/Stores/Buying";
import { ChemicalsStock } from "../../views/Stores/ChemicalsStock";
import { CreateMixture } from "../../views/Stores/CreateMixture";
import { EritmaPage } from "../../views/Stores/Eritma";
import { MixturesPage } from "../../views/Stores/Mixtures";
import { Transfers } from "../../views/Stores/Transfers";

export const chemicalStore = [
  {
    parent: "chemical_store",
    link: "list",
    sidebar: true,
    title: "catalogies",
    parent_icon: "/images/store_chemical.png",
    icon: "/images/catalogue.png",
    element: "",
    auth: true,
    permissions: ["view_page"],
    children: [
      {
        parent: "chemical_store/list",
        link: "chemicals",
        title: "chemicals",
        childLink: "chemicals",
        path: "chemical_store/chemicals",
        icon: "/images/chemical.webp",
      },
      {
        parent: "chemical_store/mixtures",
        link: "mixtures",
        title: "chemicals_mixtures",
        childLink: "mixtures",
        path: "chemical_store/mixtures",
        icon: "/images/mixtures.png",
      },
      {
        parent: "chemical_store/mixture_create",
        link: "mixture_create",
        title: "chemicals_mixture_create",
        childLink: "mixture_create",
        path: "chemical_store/mixture_create",
        icon: "/images/create.webp",
      },
    ],
  },
  {
    parent: "chemical_store",
    link: "documents",
    sidebar: true,
    title: "Документы",
    icon: "/images/documents.webp",
    element: "",
    auth: true,
    permissions: ["view_page"],
    children: [
      {
        parent: "chemical_store/list",
        link: "transfers",
        title: "Внутреннее примешенные",
        childLink: "transfers",
        path: "chemical_store/transfers",
        icon: "/images/transfers.png",
      },
      {
        parent: "chemical_store/list",
        link: "buying",
        title: "Документ покупки",
        childLink: "buying",
        path: "chemical_store/buying",
        icon: "/images/store.png",
      },
    ],
  },
  {
    parent: "chemical_store",
    link: "reports",
    sidebar: true,
    title: "Отчёты",
    icon: "/images/report.png",
    element: "",
    auth: true,
    permissions: ["view_page"],
    children: [
      {
        parent: "chemical_store/list",
        link: "chemical_stock",
        title: "Остатки химикатов",
        childLink: "chemical_stock",
        path: "chemical_store/chemical_stock",
        icon: "/images/report.png",
      },
    ],
  },
  {
    parent: "chemical_store",
    parent_link: "chemical_store/list",
    link: "chemicals",
    sidebar: false,
    element: <EritmaPage />,
    permissions: ["view_page"],
  },
  {
    parent: "chemical_store",
    parent_link: "chemical_store/list",
    link: "mixtures",
    sidebar: false,
    element: <MixturesPage />,
    permissions: ["view_page"],
  },
  {
    parent: "chemical_store",
    parent_link: "chemical_store/list",
    link: "mixture_create",
    sidebar: false,
    element: <CreateMixture />,
    permissions: ["view_page"],
  },
  {
    parent: "chemical_store",
    parent_link: "chemical_store/documents",
    link: "transfers",
    sidebar: false,
    element: <Transfers />,
    permissions: ["view_page"],
  },
  {
    parent: "chemical_store",
    parent_link: "chemical_store/documents",
    link: "buying",
    sidebar: false,
    element: <BuyingChemicals />,
    permissions: ["view_page"],
  },
  {
    parent: "chemical_store",
    parent_link: "chemical_store/reports",
    link: "chemical_stock",
    sidebar: false,
    element: <ChemicalsStock />,
  },
];
