import * as yup from "yup";
export const Validation = () => {
  return yup.object().shape({
    HAMID: yup.string().optional(),
    RENKDERINLIGIID: yup.number().required("Обязательное поле!"),
    ISLEMTIPIID: yup.number().required("Обязательное поле!"),
    BIRIMFIYAT: yup.string().required("Обязательное поле!"),
    PUS: yup.number().optional(),
    FEINE: yup.number().optional(),
    IPTALKILO: yup.number().optional(),
    BRUTKILO: yup.number().optional(),
    IPTALMETRE: yup.number().optional(),
    KALITEID: yup.string().required("Обязательное поле!"),
    DOVIZID: yup.string().optional(),
    LABRECETEKODU: yup.string().required("Обязательное поле!"),
    SIPARISPROSESID: yup.number().optional(),
    RENKID: yup.number().optional(),
    NOTU: yup.string().optional(),
    PLANLAMANOTU: yup.string().optional(),
    TERMINNOTU: yup.string().optional(),
    HATAPUANICARPANI: yup.number().optional(),
    DESENID: yup.string().optional(),
    PANTONEKODU: yup.string().optional(),
    LABRECETEID: yup.number().optional(),
    HAMADI: yup.string().optional(),
    ENISTENEN: yup.string().optional(),
    GRAMAJISTENEN: yup.string().optional(),
    MUSTERISIPARISNO: yup.string().optional(),
    REFSIPARISNO: yup.number().optional(),
    SEKILADRES: yup.string().optional(),
    MELANJKODU: yup.string().optional(),
    FIREORANI: yup.number().optional(),
    DESENVARYANTID: yup.number().optional(),
    SIPARISNOTU: yup.string().optional(),
    ONAYDURUMU: yup.boolean().optional(),
    TERMINTARIHI: yup.string().optional(),
    LABRECETEATISID: yup.number().optional(),
    RECETEASAMAADI: yup.string().optional(),
    ADET: yup.mixed().optional(),
    BOYASIPARISKAYITID: yup.number().optional(),
    DEGISIMLOG: yup.string().optional(),
    DINLENMISGRAMAJ: yup.string().optional(),
    BASKIBIRIMFIYATDOVIZID: yup.string().optional(),
    FASONBIRIMFIYATDOVIZID: yup.string().optional(),
    FATURAEDILECEKMIKTARTIPI: yup.number().optional(),
    HAMSTOKBIRIMID: yup.number().optional(),
    SIRANO: yup.number().optional(),
    FIRMASEVKADRESIID: yup.number().optional(),
    INSERTKULLANICIID: yup.number().optional(),
    ORMESIPARISDETAYID: yup.number().optional(),
    BOYASIPARISDETAYID: yup.number().optional(),
    LABRECETEATISNO: yup.string().optional(),
    RENKDERINLIGIADI: yup.string().optional(),
    SIPARISKILO: yup.number().optional(),
    SIPARISBRUTKILO: yup.number().optional(),
    REFERANSSIPARISNO: yup.string().optional(),
    MAXIMUMFIREORANI: yup.number().optional(),
    ATISNO: yup.string().optional(),
    SIPARISPROSESADI: yup.string().optional(),
  });
};
